namespace GoblinStronghold.Simulation;

public enum SimulationEventKind
{
    FoodGathered = 1,
    ActorAte = 2,
    StorageZoneCreated = 3,
    ItemPickedUp = 4,
    ItemStored = 5,
    ItemStackDepleted = 6,
    CommandRejected = 7,
    ActorDied = 8,
    HumanVillageAlerted = 9,
    HumanGuardHitGoblin = 10,
    GoblinHitHumanGuard = 11,
    HumanDied = 12,
    MoveOrdered = 13,
    MoveCompleted = 14,
    ActorProvisionedFood = 15,
    ActorCollectedWater = 16,
    ActorDrank = 17,
    ConstructionCompleted = 18,
    WorkDesignationCreated = 19,
    WorkDesignationRemoved = 20,
    StoragePullConfigured = 21,
    RaidPreparationStarted = 22,
    RaidDeparted = 23,
    ConstructionOrdered = 24,
    ConstructionMaterialDelivered = 25,
    ActorCollapsed = 26,
    StorageHaulerConfigured = 27,
    StorageSourceConfigured = 28,
    StoragePriorityConfigured = 29,
    ResourcePriorityConfigured = 30,
    ConstructionPriorityConfigured = 31,
    StorageMineralFilterConfigured = 32,
    WorkPriorityConfigured = 33,
    WorkSuspensionConfigured = 34,
    ItemDropped = 35,
    RaidVictory = 36,
    RaidDefeated = 37,
    PopulationTargetConfigured = 38,
    GoblinBudCreated = 39,
    GoblinBorn = 40,
    AnimalHitGoblin = 41,
    AnimalBorn = 42,
    AnimalDied = 43,
    AnimalHunted = 44,
    CraftingOrdered = 45,
    CraftingMaterialDelivered = 46,
    CraftingCompleted = 47,
    ActorCollectedStoneAmmo = 48,
    CorpseConsumed = 49,
    GoblinHitHumanCivilian = 50,
}

public readonly record struct SimulationEvent(
    ulong Sequence,
    SimulationTick Tick,
    SimulationEventKind Kind,
    EntityId Subject,
    EntityId Target,
    int Amount)
{
    public ConstructionKind? Construction { get; init; }
}
