<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoblinStronghold.Simulation\GoblinStronghold.Simulation.csproj" />
    <EmbeddedResource Include="Content\title-splashes.pl.txt"
                      LogicalName="GoblinStronghold.GodotClient.Content.title-splashes.pl.txt"
                      WithCulture="false" />
    <EmbeddedResource Include="Content\title-splashes.en.txt"
                      LogicalName="GoblinStronghold.GodotClient.Content.title-splashes.en.txt"
                      WithCulture="false" />
  </ItemGroup>
</Project>
